export class TestPost {
    testPostOne: any = {
        "CurrentPage": 1,
        "TotalPages": 3614,
        "Bans": [
            {
                "Type": "PROBATION",
                "PostId": 486930244,
                "Date": "2018-08-10T14:23:00",
                "HorribleJerk": "big crush on Chad OMG",
                "HorribleJerkId": 75172,
                "PunishmentReason": "Please chill out with these weak ass burns outside of the chat thread. User loses posting privileges for 6 hours.",
                "RequestedBy": "Gigi Galli",
                "RequestedById": 42231,
                "ApprovedBy": "Gigi Galli",
                "ApprovedById": 42231
            },
            {
                "Type": "PROBATION",
                "PostId": 486928715,
                "Date": "2018-08-10T14:02:00",
                "HorribleJerk": "goethe.cx",
                "HorribleJerkId": 209706,
                "PunishmentReason": "<img src=\"https://fi.somethingawful.com/images/smilies/emot-yikes.gif\" border=\"0\" alt=\"\" title=\":yikes:\"> User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486925634,
                "Date": "2018-08-10T12:29:00",
                "HorribleJerk": "KingFisher",
                "HorribleJerkId": 105034,
                "PunishmentReason": "White supremacy or trolling, either way this post is dogshit. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486883810,
                "Date": "2018-08-10T12:20:00",
                "HorribleJerk": "Mill Town",
                "HorribleJerkId": 95629,
                "PunishmentReason": "Use the real ignore list. or don't. you coward. User loses posting privileges for 6 hours.",
                "RequestedBy": "Jose",
                "RequestedById": 121245,
                "ApprovedBy": "Jose",
                "ApprovedById": 121245
            },
            {
                "Type": "PROBATION",
                "PostId": 486882647,
                "Date": "2018-08-10T12:19:00",
                "HorribleJerk": "Sorority Fister",
                "HorribleJerkId": 223219,
                "PunishmentReason": "Take a break. User loses posting privileges for 6 hours.",
                "RequestedBy": "Jose",
                "RequestedById": 121245,
                "ApprovedBy": "Jose",
                "ApprovedById": 121245
            },
            {
                "Type": "PROBATION",
                "PostId": 486916567,
                "Date": "2018-08-10T10:56:00",
                "HorribleJerk": "Max Facetime",
                "HorribleJerkId": 150418,
                "PunishmentReason": "Shut the fuck up. User loses posting privileges for 6 hours.",
                "RequestedBy": "graph",
                "RequestedById": 105961,
                "ApprovedBy": "graph",
                "ApprovedById": 105961
            },
            {
                "Type": "PROBATION",
                "PostId": 486897038,
                "Date": "2018-08-10T09:45:00",
                "HorribleJerk": "feelix",
                "HorribleJerkId": 219842,
                "PunishmentReason": "Critical shitposting. User loses posting privileges for 6 hours.",
                "RequestedBy": "Lumpy the Cook",
                "RequestedById": 172204,
                "ApprovedBy": "Lumpy the Cook",
                "ApprovedById": 172204
            },
            {
                "Type": "PROBATION",
                "PostId": 486922318,
                "Date": "2018-08-10T09:36:00",
                "HorribleJerk": "Party Plane Jones",
                "HorribleJerkId": 119284,
                "PunishmentReason": "We should, in fact, stop there. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486898564,
                "Date": "2018-08-10T02:48:00",
                "HorribleJerk": "American McGay",
                "HorribleJerkId": 161228,
                "PunishmentReason": "It is a honest question, and many people do care. User loses posting privileges for 6 hours.",
                "RequestedBy": "VideoGames",
                "RequestedById": 40838,
                "ApprovedBy": "VideoGames",
                "ApprovedById": 40838
            },
            {
                "Type": "PROBATION",
                "PostId": 486898856,
                "Date": "2018-08-10T02:41:00",
                "HorribleJerk": "Chill Penguin",
                "HorribleJerkId": 47237,
                "PunishmentReason": "Chill penguin be more chill. User loses posting privileges for 6 hours.",
                "RequestedBy": "VideoGames",
                "RequestedById": 40838,
                "ApprovedBy": "VideoGames",
                "ApprovedById": 40838
            },
            {
                "Type": "PROBATION",
                "PostId": 486915029,
                "Date": "2018-08-10T00:05:00",
                "HorribleJerk": "Martin BadClixx",
                "HorribleJerkId": 188240,
                "PunishmentReason": "You edited this multiple times, and yet... I am obliged to mark this occasion of embarrassing failure. User loses posting privileges for 6 hours.",
                "RequestedBy": "SKULL.GIF",
                "RequestedById": 220243,
                "ApprovedBy": "SKULL.GIF",
                "ApprovedById": 220243
            },
            {
                "Type": "PROBATION",
                "PostId": 486914598,
                "Date": "2018-08-09T23:54:00",
                "HorribleJerk": "Hostess Snack Cake",
                "HorribleJerkId": 185247,
                "PunishmentReason": "Reversal of fortune. User loses posting privileges for 6 hours.",
                "RequestedBy": "SKULL.GIF",
                "RequestedById": 220243,
                "ApprovedBy": "SKULL.GIF",
                "ApprovedById": 220243
            },
            {
                "Type": "PROBATION",
                "PostId": 486914354,
                "Date": "2018-08-09T23:40:00",
                "HorribleJerk": "Wulfolme",
                "HorribleJerkId": 136212,
                "PunishmentReason": "<img src=\"https://i.imgur.com/ugiJscc.jpg\" alt=\"\" class=\"img\" border=\"0\"> User loses posting privileges for 6 hours.",
                "RequestedBy": "logikv9",
                "RequestedById": 148067,
                "ApprovedBy": "logikv9",
                "ApprovedById": 148067
            },
            {
                "Type": "PROBATION",
                "PostId": 486912406,
                "Date": "2018-08-09T22:24:00",
                "HorribleJerk": "almost there",
                "HorribleJerkId": 219181,
                "PunishmentReason": "You sound upset. User loses posting privileges for 6 hours.",
                "RequestedBy": "Captain_Maclaine",
                "RequestedById": 26179,
                "ApprovedBy": "Captain_Maclaine",
                "ApprovedById": 26179
            },
            {
                "Type": "PROBATION",
                "PostId": 486907360,
                "Date": "2018-08-09T22:14:00",
                "HorribleJerk": "PoPcornTG",
                "HorribleJerkId": 113104,
                "PunishmentReason": "<img src=\"https://i.imgur.com/8k3faVH.gif\" alt=\"\" class=\"img\" border=\"0\"> User loses posting privileges for 6 hours.",
                "RequestedBy": "logikv9",
                "RequestedById": 148067,
                "ApprovedBy": "logikv9",
                "ApprovedById": 148067
            },
            {
                "Type": "PROBATION",
                "PostId": 486910046,
                "Date": "2018-08-09T20:14:00",
                "HorribleJerk": "binaryslacker",
                "HorribleJerkId": 179196,
                "PunishmentReason": "<img src=\"https://fi.somethingawful.com/flags/4c/0a/0000010105.gif?by=Fart%20Jesus%20LOL\" alt=\"\" class=\"img\" border=\"0\" title=\"flag by: Fart Jesus LOL\"> User loses posting privileges for 6 hours.",
                "RequestedBy": "PinkoBastard",
                "RequestedById": 168023,
                "ApprovedBy": "PinkoBastard",
                "ApprovedById": 168023
            },
            {
                "Type": "PROBATION",
                "PostId": 486897020,
                "Date": "2018-08-09T19:23:00",
                "HorribleJerk": "The Sicilian",
                "HorribleJerkId": 102701,
                "PunishmentReason": "Enjoy your money, babe. Hopefully you can buy a personality. User loses posting privileges for 1 month.",
                "RequestedBy": "Adiabatic",
                "RequestedById": 127562,
                "ApprovedBy": "FactsAreUseless",
                "ApprovedById": 172615
            },
            {
                "Type": "PROBATION",
                "PostId": 486895371,
                "Date": "2018-08-09T19:23:00",
                "HorribleJerk": "CAPS LOCK BROKEN",
                "HorribleJerkId": 91803,
                "PunishmentReason": "Awful, awful posting. User loses posting privileges for 3 days.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "FactsAreUseless",
                "ApprovedById": 172615
            },
            {
                "Type": "PROBATION",
                "PostId": 486873817,
                "Date": "2018-08-09T19:23:00",
                "HorribleJerk": "Jack Forge",
                "HorribleJerkId": 190099,
                "PunishmentReason": "All you needed to do is acknowledge this stuff and not double down. Especially considering it was one person requesting that 'hey, do not use this word'. User loses posting privileges for 1 day.",
                "RequestedBy": "VideoGames",
                "RequestedById": 40838,
                "ApprovedBy": "FactsAreUseless",
                "ApprovedById": 172615
            },
            {
                "Type": "PROBATION",
                "PostId": 486883505,
                "Date": "2018-08-09T19:23:00",
                "HorribleJerk": "John Smith",
                "HorribleJerkId": 214054,
                "PunishmentReason": "I'm not saying every post you make is wrong, but every post you make is annoying to everyone. User loses posting privileges for 3 days.",
                "RequestedBy": "Moneyball",
                "RequestedById": 81453,
                "ApprovedBy": "FactsAreUseless",
                "ApprovedById": 172615
            },
            {
                "Type": "PROBATION",
                "PostId": 486872577,
                "Date": "2018-08-09T19:23:00",
                "HorribleJerk": "Plutonis",
                "HorribleJerkId": 174355,
                "PunishmentReason": "Stop posting so badly. User loses posting privileges for 1 week.",
                "RequestedBy": "Matoi Ryuko",
                "RequestedById": 46995,
                "ApprovedBy": "FactsAreUseless",
                "ApprovedById": 172615
            },
            {
                "Type": "PROBATION",
                "PostId": 486626775,
                "Date": "2018-08-09T19:23:00",
                "HorribleJerk": "Kerning Chameleon",
                "HorribleJerkId": 214585,
                "PunishmentReason": "Please never post anything like this again. User loses posting privileges for 1 week.",
                "RequestedBy": "Matoi Ryuko",
                "RequestedById": 46995,
                "ApprovedBy": "FactsAreUseless",
                "ApprovedById": 172615
            },
            {
                "Type": "PROBATION",
                "PostId": 486870008,
                "Date": "2018-08-09T19:23:00",
                "HorribleJerk": "Bathtub Cheese",
                "HorribleJerkId": 137575,
                "PunishmentReason": "Need a bit longer time off, actually. User loses posting privileges for 1 day.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "FactsAreUseless",
                "ApprovedById": 172615
            },
            {
                "Type": "PROBATION",
                "PostId": 486908124,
                "Date": "2018-08-09T19:10:00",
                "HorribleJerk": "feelix",
                "HorribleJerkId": 219842,
                "PunishmentReason": "Then contribute something useful. Go! User loses posting privileges for 6 hours.",
                "RequestedBy": "GRINDCORE MEGGIDO",
                "RequestedById": 61923,
                "ApprovedBy": "GRINDCORE MEGGIDO",
                "ApprovedById": 61923
            },
            {
                "Type": "PROBATION",
                "PostId": 486899919,
                "Date": "2018-08-09T15:09:00",
                "HorribleJerk": "Crankit",
                "HorribleJerkId": 172295,
                "PunishmentReason": "Dogshit posting. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486885493,
                "Date": "2018-08-09T15:09:00",
                "HorribleJerk": "everythingWasBees",
                "HorribleJerkId": 195432,
                "PunishmentReason": "Do not be rude. User loses posting privileges for 6 hours.",
                "RequestedBy": "Matoi Ryuko",
                "RequestedById": 46995,
                "ApprovedBy": "Matoi Ryuko",
                "ApprovedById": 46995
            },
            {
                "Type": "PROBATION",
                "PostId": 486901230,
                "Date": "2018-08-09T14:55:00",
                "HorribleJerk": "Quotey",
                "HorribleJerkId": 101726,
                "PunishmentReason": "Do not encourage self-harm. User loses posting privileges for 6 hours.",
                "RequestedBy": "Captain_Maclaine",
                "RequestedById": 26179,
                "ApprovedBy": "Captain_Maclaine",
                "ApprovedById": 26179
            },
            {
                "Type": "PROBATION",
                "PostId": 486894660,
                "Date": "2018-08-09T13:26:00",
                "HorribleJerk": "mcmagic",
                "HorribleJerkId": 57898,
                "PunishmentReason": "<img src=\"https://fi.somethingawful.com/images/smilies/emot-yikes.gif\" border=\"0\" alt=\"\" title=\":yikes:\"> User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486898477,
                "Date": "2018-08-09T13:24:00",
                "HorribleJerk": "Crowsbeak",
                "HorribleJerkId": 190503,
                "PunishmentReason": "Low content post. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486878989,
                "Date": "2018-08-09T12:53:00",
                "HorribleJerk": "Max Facetime",
                "HorribleJerkId": 150418,
                "PunishmentReason": "Jesus Christ, shut the fuck up. User loses posting privileges for 6 hours.",
                "RequestedBy": "graph",
                "RequestedById": 105961,
                "ApprovedBy": "graph",
                "ApprovedById": 105961
            },
            {
                "Type": "PROBATION",
                "PostId": 486896714,
                "Date": "2018-08-09T12:39:00",
                "HorribleJerk": "feelix",
                "HorribleJerkId": 219842,
                "PunishmentReason": "Get a clue. User loses posting privileges for 6 hours.",
                "RequestedBy": "In Training",
                "RequestedById": 138102,
                "ApprovedBy": "In Training",
                "ApprovedById": 138102
            },
            {
                "Type": "PROBATION",
                "PostId": 486892652,
                "Date": "2018-08-09T12:28:00",
                "HorribleJerk": "Rent-A-Cop",
                "HorribleJerkId": 66302,
                "PunishmentReason": "Might be true but not relevant to the (bad) content of posts. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486893264,
                "Date": "2018-08-09T12:25:00",
                "HorribleJerk": "CAPS LOCK BROKEN",
                "HorribleJerkId": 91803,
                "PunishmentReason": "Placeholder. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486895073,
                "Date": "2018-08-09T11:26:00",
                "HorribleJerk": "A Man and his Hog",
                "HorribleJerkId": 223035,
                "PunishmentReason": "Not being excellent to each other. User loses posting privileges for 6 hours.",
                "RequestedBy": "Athanatos",
                "RequestedById": 97970,
                "ApprovedBy": "Athanatos",
                "ApprovedById": 97970
            },
            {
                "Type": "PROBATION",
                "PostId": 486140924,
                "Date": "2018-08-09T09:56:00",
                "HorribleJerk": "CMD",
                "HorribleJerkId": 212450,
                "PunishmentReason": "Die properly. User loses posting privileges for 6 hours.",
                "RequestedBy": "PinkoBastard",
                "RequestedById": 168023,
                "ApprovedBy": "PinkoBastard",
                "ApprovedById": 168023
            },
            {
                "Type": "PROBATION",
                "PostId": 486888619,
                "Date": "2018-08-09T09:29:00",
                "HorribleJerk": "not a cult",
                "HorribleJerkId": 145243,
                "PunishmentReason": "Low effort shitpost. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486890746,
                "Date": "2018-08-09T09:19:00",
                "HorribleJerk": "Absurd Alhazred",
                "HorribleJerkId": 162211,
                "PunishmentReason": "Isn't US State and Local Politics. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486890982,
                "Date": "2018-08-09T09:19:00",
                "HorribleJerk": "VitalSigns",
                "HorribleJerkId": 179121,
                "PunishmentReason": "Isn't US State and Local Politics. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486890945,
                "Date": "2018-08-09T09:18:00",
                "HorribleJerk": "sexpig by night",
                "HorribleJerkId": 179593,
                "PunishmentReason": "Isn't US State and Local Politics. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            },
            {
                "Type": "PROBATION",
                "PostId": 486890520,
                "Date": "2018-08-09T08:57:00",
                "HorribleJerk": "monkeu",
                "HorribleJerkId": 10384,
                "PunishmentReason": "Spreading your terrible posts out over half a day is better than spamming but your gimmick is still incredibly fucking tiresome. User loses posting privileges for 6 hours.",
                "RequestedBy": "Henchman of Santa",
                "RequestedById": 167099,
                "ApprovedBy": "Henchman of Santa",
                "ApprovedById": 167099
            },
            {
                "Type": "AUTOBAN",
                "PostId": 486883684,
                "Date": "2018-08-08T23:24:00",
                "HorribleJerk": "TheToxicEuphoria",
                "HorribleJerkId": 132579,
                "PunishmentReason": "Breaking the rules with a stupendous thread!",
                "RequestedBy": "radium",
                "RequestedById": 26473,
                "ApprovedBy": "radium",
                "ApprovedById": 26473
            },
            {
                "Type": "PROBATION",
                "PostId": 486881024,
                "Date": "2018-08-08T22:50:00",
                "HorribleJerk": "Sapozhnik",
                "HorribleJerkId": 72615,
                "PunishmentReason": "That 40 year old boomer. User loses posting privileges for 6 hours.",
                "RequestedBy": "SKULL.GIF",
                "RequestedById": 220243,
                "ApprovedBy": "SKULL.GIF",
                "ApprovedById": 220243
            },
            {
                "Type": "PROBATION",
                "PostId": 486882839,
                "Date": "2018-08-08T22:44:00",
                "HorribleJerk": "Mariana Horchata",
                "HorribleJerkId": 138250,
                "PunishmentReason": "Cursed and impermissible. User loses posting privileges for 6 hours.",
                "RequestedBy": "SKULL.GIF",
                "RequestedById": 220243,
                "ApprovedBy": "SKULL.GIF",
                "ApprovedById": 220243
            },
            {
                "Type": "PROBATION",
                "PostId": 486879596,
                "Date": "2018-08-08T22:23:00",
                "HorribleJerk": "theflyingexecutive",
                "HorribleJerkId": 115051,
                "PunishmentReason": "<img src=\"https://fi.somethingawful.com/safs/smilies/6/6/chloe.001.png\" border=\"0\" alt=\"\" title=\":chloe:\"> User loses posting privileges for 6 hours.",
                "RequestedBy": "Sheng-Ji Yang",
                "RequestedById": 209029,
                "ApprovedBy": "Sheng-Ji Yang",
                "ApprovedById": 209029
            },
            {
                "Type": "PROBATION",
                "PostId": 486877202,
                "Date": "2018-08-08T19:20:00",
                "HorribleJerk": "Long Waffle Beard",
                "HorribleJerkId": 42046,
                "PunishmentReason": "Barnacle Jim. User loses posting privileges for 6 hours.",
                "RequestedBy": "spb",
                "RequestedById": 206334,
                "ApprovedBy": "spb",
                "ApprovedById": 206334
            },
            {
                "Type": "PROBATION",
                "PostId": 486862066,
                "Date": "2018-08-08T18:10:00",
                "HorribleJerk": "Tenkaris",
                "HorribleJerkId": 92225,
                "PunishmentReason": "Please read the rules. User loses posting privileges for 6 hours.",
                "RequestedBy": "Matoi Ryuko",
                "RequestedById": 46995,
                "ApprovedBy": "Matoi Ryuko",
                "ApprovedById": 46995
            },
            {
                "Type": "PROBATION",
                "PostId": 486872577,
                "Date": "2018-08-08T17:14:00",
                "HorribleJerk": "Plutonis",
                "HorribleJerkId": 174355,
                "PunishmentReason": "Harassment. User loses posting privileges for 6 hours.",
                "RequestedBy": "Matoi Ryuko",
                "RequestedById": 46995,
                "ApprovedBy": "Matoi Ryuko",
                "ApprovedById": 46995
            },
            {
                "Type": "PROBATION",
                "PostId": 486863437,
                "Date": "2018-08-08T17:14:00",
                "HorribleJerk": "Space Flower",
                "HorribleJerkId": 211933,
                "PunishmentReason": "Chill out. User loses posting privileges for 6 hours.",
                "RequestedBy": "Matoi Ryuko",
                "RequestedById": 46995,
                "ApprovedBy": "Matoi Ryuko",
                "ApprovedById": 46995
            },
            {
                "Type": "PROBATION",
                "PostId": 486872064,
                "Date": "2018-08-08T15:34:00",
                "HorribleJerk": "hevnz 2 murgatroyd",
                "HorribleJerkId": 222685,
                "PunishmentReason": "GBS. User loses posting privileges for 6 hours.",
                "RequestedBy": "PinkoBastard",
                "RequestedById": 168023,
                "ApprovedBy": "PinkoBastard",
                "ApprovedById": 168023
            },
            {
                "Type": "PROBATION",
                "PostId": 486865260,
                "Date": "2018-08-08T15:31:00",
                "HorribleJerk": "Wooten",
                "HorribleJerkId": 65556,
                "PunishmentReason": "Fell for the bait post. User loses posting privileges for 6 hours.",
                "RequestedBy": "Party Plane Jones",
                "RequestedById": 119284,
                "ApprovedBy": "Party Plane Jones",
                "ApprovedById": 119284
            }
        ]
    }
}